

# trajectory processing configuration
#trajectory_velocity_scaling : 1.0

# evaluate the plan trajectory
#max_plan_steps : 30
#max_cartesion_plan_steps : 120

calibration_adjust_x : -0.015
calibration_adjust_y : 0.07
calibration_adjust_z : 0.0

confirm_act : False
debug_print : False
